<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-05T08:19:22 IST" name="Suite" finished-at="2023-04-05T08:19:33 IST" duration-ms="11657">
    <groups>
    </groups>
    <test started-at="2023-04-05T08:19:22 IST" name="Test" finished-at="2023-04-05T08:19:33 IST" duration-ms="11657">
      <class name="Test_Class.post_TC1">
        <test-method signature="orchestrator()[pri:0, instance:Test_Class.post_TC1@7c214cc0]" started-at="2023-04-05T08:19:31 IST" name="orchestrator" finished-at="2023-04-05T08:19:33 IST" duration-ms="2060" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[2023-04-05 expected [null] but found [2023-04-05]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 2023-04-05 expected [null] but found [2023-04-05]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotSame(Assert.java:1573)
at org.testng.Assert.assertNull(Assert.java:1506)
at Test_Class.post_TC1.responseBodyValidator(post_TC1.java:70)
at Test_Class.post_TC1.orchestrator(post_TC1.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orchestrator -->
      </class> <!-- Test_Class.post_TC1 -->
      <class name="Test_Class.get_TC1">
        <test-method signature="orchestrator()[pri:0, instance:Test_Class.get_TC1@59e32960]" started-at="2023-04-05T08:19:29 IST" name="orchestrator" finished-at="2023-04-05T08:19:31 IST" duration-ms="2649" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orchestrator -->
      </class> <!-- Test_Class.get_TC1 -->
      <class name="Test_Class.put_TC1">
        <test-method signature="orchestrator()[pri:0, instance:Test_Class.put_TC1@60b4beb4]" started-at="2023-04-05T08:19:22 IST" name="orchestrator" finished-at="2023-04-05T08:19:27 IST" duration-ms="4782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orchestrator -->
      </class> <!-- Test_Class.put_TC1 -->
      <class name="Test_Class.patch_TC1">
        <test-method signature="orchestrator()[pri:0, instance:Test_Class.patch_TC1@3561c410]" started-at="2023-04-05T08:19:27 IST" name="orchestrator" finished-at="2023-04-05T08:19:29 IST" duration-ms="1929" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orchestrator -->
      </class> <!-- Test_Class.patch_TC1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
